GET http://localhost:8080/init/initAdmin


###registration user
POST http://localhost:8080/auth/registration
Content-Type: application/json


{
  "name" : "faeefeafa",
  "surname" : "aegfaeg",
  "email": "user@gmail.com",
  "password" : "1111"
}







