POST http://localhost:8082/brand/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1NjQxNDIsImV4cCI6MTY1NTU2Nzc0MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.XiyK2UGPpyQmy8GkFA9AgP5EVf750DSq0SFH4YB3G40

{
  "name" : "iPhone"
}
###

GET http://localhost:8082/brand/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1NjA0NDksImV4cCI6MTY1NTU2NDA0OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ._ZzCCmPxP7hxoT9MZvpbPXP8gj1IhQyqTJU-0YpqQSM