POST http://localhost:8081/category/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1MTg5NTcsImV4cCI6MTY1NTUyMjU1NywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.b1-kaqUW1-giKUztWefPSrHqJuBoCxzKugKfCzZp4RE

{
  "key" : "tugmachali",
  "nameUz" : "tugmachali_uz",
  "nameRu" : "tugmachali_ru",
  "nameEn" : "tugmachali_en"

}