
### create category and parentCategory in Admin
POST http://localhost:8085/category/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYxNTMyMzYsImV4cCI6MTY1NjE1NjgzNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.p4qPeFkVayiL7KgUHBk5IQMcNWLCcEhg2QfiyB7iaiU

{
  "key" : "iPhone",
  "nameUz" : "iPhone",
  "nameRu" : "iPhone",
  "nameEn" : "iPhone"

}



###get category list in Admin
GET http://localhost:8085/category/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYxNTMyMzYsImV4cCI6MTY1NjE1NjgzNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.p4qPeFkVayiL7KgUHBk5IQMcNWLCcEhg2QfiyB7iaiU


###get category list users in current language
GET http://localhost:8085/category/public
Accept-Language: UZ