
### create category and parentCategory in Admin
POST http://localhost:8082/category/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1ODkxMjUsImV4cCI6MTY1NTU5MjcyNSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiU0VMTEVSIn0.WX9DUlnYs84e1XSU4ViK7fYNWtSuOr-lKmnqn7p-AOE

{
  "key" : "Tablets",
  "nameUz" : "Planshetlar",
  "nameRu" : "Таблетки",
  "nameEn" : "Tablets"
}



###get category list in Admin
GET http://localhost:8082/category/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1NjA0NDksImV4cCI6MTY1NTU2NDA0OSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ._ZzCCmPxP7hxoT9MZvpbPXP8gj1IhQyqTJU-0YpqQSM


###get category list users in current language
GET http://localhost:8082/category/public
Accept-Language: EN