### create color in Admin
POST http://localhost:8085/color/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU5MzE3MDksImV4cCI6MTY1NTkzNTMwOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MThkMzgyNDAxODE4ZDM4OWFmZTAwMDAiLCJyb2xlIjoiQURNSU4ifQ.26Wh6W70ijykkXiYlOSj43hpL37ZKhdyRJ2Zx1AbprA

{
  "key" : "Oq",
  "nameUz" : "Oq_uz",
  "nameRu" : "Oq_uz",
  "nameEn" : "Oq_en",
  "code" : "daedaeda"
}

### get color list in admin
GET http://localhost:8082/color/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1NjE3ODUsImV4cCI6MTY1NTU2NTM4NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.2870xu4wAVmgADaRBgfpjvfF2Kh68Dy1NLCEx49VV_Y

###get color list users in current language
GET http://localhost:8082/color/public
Accept-Language: RU