### create color in Admin
POST http://localhost:8085/color/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU2NjU5NTgsImV4cCI6MTY1NTY2OTU1OCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiZmY4MDgwODE4MTdkMTE0ODAxODE3ZDEyMTQ2NjAwMDAiLCJyb2xlIjoiQURNSU4ifQ.N2K4Kot2qeLyu70_RqOx6YYuJrnoG4WFNP0UjoVU6AU

{
  "key" : "Oq",
  "nameUz" : "Oq_uz",
  "nameRu" : "Oq_uz",
  "nameEn" : "Oq_en",
  "code" : "daedaeda"
}

### get color list in admin
GET http://localhost:8082/color/admin
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1NjE3ODUsImV4cCI6MTY1NTU2NTM4NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.2870xu4wAVmgADaRBgfpjvfF2Kh68Dy1NLCEx49VV_Y

###get color list users in current language
GET http://localhost:8082/color/public
Accept-Language: RU