POST http://localhost:8085/productAdd/admin/productAddAttach
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY2MDY5MDYsImV4cCI6MTY1NjYxMDUwNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.QqN3Xyv0Sdqg8RDk5bZmx2pFJ0SHcR-QkxqGpWtAlGI

{
  "productId": "8a8a81cb819ae81601819aeab6dc0003",
  "colorId": "1",
  "attachList": [
    "4e99d749-bf49-4dc9-989f-cb5a23cccdbb"
    ]
}


###
PUT http://localhost:8085/productAdd/admin/update/8a8a81cb819a8f2901819a8f55bb0000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY2MDY5MDYsImV4cCI6MTY1NjYxMDUwNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.QqN3Xyv0Sdqg8RDk5bZmx2pFJ0SHcR-QkxqGpWtAlGI




###public getProductList
GET http://localhost:8085/productAdd/list
