
### product create Profale role Seller
POST http://localhost:8082/product/seller
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1ODk5ODAsImV4cCI6MTY1NTU5MzU4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiU0VMTEVSIn0.-gVVSI7p30YGrGvhToTpkkSWYhUpz4DzR1NqcXsmuNk

{
  "model": "MacBook Air",
  "analysis": "cffkjefbekjfwkfbowe",
  "technicalSpecification": "dasdasdasdasdasd",
  "ram": 8,
  "memory": 256,
  "price" : 9000,
  "brandId" : 1,
  "categoryParentId" : 1,
  "categoryId" : 4,
  "colorList": [
    1,
    2
  ]

}

### product status update On sale OR Not on sale
PUT http://localhost:8082/product/seller/status/ff8080818178deca018178e742aa0001
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1ODk5ODAsImV4cCI6MTY1NTU5MzU4MCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiU0VMTEVSIn0.-gVVSI7p30YGrGvhToTpkkSWYhUpz4DzR1NqcXsmuNk


###product visible update ture or false
DELETE http://localhost:8082/product/seller/delete/ff808081817852420181786295a40002
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU1Njk1MDQsImV4cCI6MTY1NTU3MzEwNCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiU0VMTEVSIn0.7D_APJh4LPRvvkuiFvh5S_fnVAKZYBHadd_vNHl6V1M

###pagination product
GET http://localhost:8082/product/pagination?page=1&size=2
Content-Type: application/json


###get product list brand and category key on sale
GET http://localhost:8082/product/list/?brand=Apple&categoryKey=Mac



###get product order by date on sale
GET http://localhost:8082/product/list
