POST http://localhost:8085/productAdd/admin/productAddAttach
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYxNTgzMzIsImV4cCI6MTY1NjE2MTkzMiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.NQd1WI2Take82XDsg-hPc70wXc652otTL2I2mzXoma8

{
  "productId": "8a8a81cb819a6c9b01819a7040150002",
  "colorId": "1",
  "attachList": [
    "94203238-bddf-4038-a20e-33a489cd6f55"]
}


###
PUT http://localhost:8085/productAdd/admin/update/8a8a81cb819a8f2901819a8f55bb0000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTYxNTM1MjksImV4cCI6MTY1NjE1NzEyOSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoiOGE4YTgxY2I4MTlhMzZjNTAxODE5YTM2ZTk4ZDAwMDAiLCJyb2xlIjoiQURNSU4ifQ.kPF6vUUZi1ZQCeht5aGlL3naBkkSYgDSBO9W3jB-RzU




###public getProductList
GET http://localhost:8085/productAdd/list
